### ISSUE TITLE
Feature request: JSON / Struct to table print

### ISSUE THREAD

**Issue by finicu212** [DrSmithFr/go-console#11]
Hello!

First of all, I want to say this is a fantastic package! The documentation is also amazing! Definitely going to use it in my upcoming project!

I have a feature request that could make this package even more great: Would it be possible to add support for easily rendering tables based on structs or JSON objects? An intuitive, reflective call like what's offered by https://github.com/lensesio/tableprinter lib would be amazing.

Here's a proposed solution that integrates seamlessly with the existing usage:

```
package main

import (
	"github.com/DrSmithFr/go-console"
	"github.com/DrSmithFr/go-console/table"
)

type Author struct {
	Name string
	Age  int
}

type Book struct {
	ISBN   *string
	Title  *string
	Author *Author
}

func main() {
	cmd := go_console.NewScript().Build()

	books := []Book{
		{ISBN: ptrStr("99921-58-10-7"), Title: ptrStr("The Divine Comedy"), Author: &Author{Name: "Dante Alighieri", Age: 56}},
		{ISBN: ptrStr("9971-5-0210-0"), Title: ptrStr("A Tale of Two Cities"), Author: &Author{Name: "Charles Dickens", Age: 58}},
		{ISBN: ptrStr("960-425-059-0"), Title: ptrStr("The Lord of the Rings"), Author: &Author{Name: "J. R. R. Tolkien", Age: 81}},
		{ISBN: ptrStr("80-902734-1-6"), Title: ptrStr("And Then There Were None"), Author: &Author{Name: "Agatha Christie", Age: 85}},
	}

	tab := table.
		NewTable().
		AddHeadersFromStructs(books).
	        AddRowsFromStructs(books)

	render := table.
		NewRender(cmd.Output).
		SetContent(tab)

	render.Render()
}
```

Once again, I love this package!!!!

**Comment by DrSmithFr** [comment]
Yes, great idea. I'll add it to my roadmap

**Comment by DrSmithFr** [comment]
### Struct / JSON parsing

I implemented the same way of parsing Struct and json used in https://github.com/lensesio/tableprinter.
(Fixing the inline capability to work with your nested pointer to struct)

### TODO

- [x] Implement struct parsing
- [ ] Implement multi-level header when using `header:"inline"`
- [ ]  ColspanTag to manage cell Colspan inside struct
- [ ]  PadTag to manage cell Padding inside struct
- [ ]  RowspanTag to manage cell Rowspan inside struct

### Questions

Hi @finicu212, What do you think about the HeaderTag, on the current version it's mandatory to defined them for fields to get displayed, should I keep the same logic ?

**Comment by finicu212** [comment]
Wow! so, I've tried the new feature out, and it is so amazing and flexible! and yes, the `header` tagging is such a good idea, I love the attention to detail. Just phenomenal

 I truly wonder why this amazing framework has such little stars and attention, because it seems so, so very polished and intuitive.
